apiVersion: v1
kind: Secret
metadata:
  name: novapay-secrets
  namespace: novapay
type: Opaque
data:
  supabase_url: aHR0cHM6Ly9sYmZvY3B2a3RmZW90ZmJrZXd2aS5zdXBhYmFzZS5jbw==
  supabase_service_key: c2Jfc2VjcmV0X3pURWlHQVotbnAwczl3bVlTTkQxZ2dfcDJnNGc1YmM=
  paystack_secret_key: c2tfdGVzdF8zMWJiYjUwZWYxN2QxNWE4ZWI1ZjcwYThmNDY2NTQ2ZDRmYjRiMmNk
